CONFIG_ADC=y

CONFIG_GPIO=y
CONFIG_TIMING_FUNCTIONS=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_BME280=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Freyr Node"
CONFIG_BT_DEVICE_APPEARANCE=832

CONFIG_BT_LL_SOFTDEVICE=y
CONFIG_BT_HCI=y

CONFIG_BT_MAX_CONN=2

CONFIG_DISPLAY=y

# Używamy uniwersalnego sterownika SSD1306 (obsługuje SH1106)
CONFIG_SSD1306=y
# Tekst i grafika
CONFIG_CHARACTER_FRAMEBUFFER=y
# Logi (usuwamy problematyczną linię, dodajemy podstawę)
CONFIG_LOG=y

CONFIG_HEAP_MEM_POOL_SIZE=4096